apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: mern-ns 
spec:
  replicas: 2
  selector:
    matchLabels:
       app/component: backend-api
  template:
    metadata:
      labels:
        app/name: mern-app
        app/component: backend-api
    spec:
      containers:
      - name: backendcontainer
        image: mukeshphulwani66/k8s-backend-demo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:    
          - secretRef:
              name: mongodb-cred
        env:
          - name: MONGOURI
            value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service:27017/mukeshdb?authSource=admin"
        ports:
        - containerPort: 5000
